### ISSUE TITLE
Error: spawn "C:\Program ENOENT

### ISSUE THREAD

**Issue by whl1295a** [elwerene/libreoffice-convert#40]
win10
node:12.19.0

Error converting file: Error: spawn "C:\Program ENOENT

**Comment by elwerene** [comment]
@whl1295a  I guess you forgot to install libreoffice or did not install in the common location

**Comment by romi103** [comment]
Same Issue. 

**Win10**
**LibreOffice v7.0.2.2** installed at C:\\Program Files\\LibreOffice\\program\\soffice.exe
**Node v14.7.0**

Error details:
```
Error converting file: Error: spawn "C:\Program ENOENT
Error: spawn "C:\Program ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn "C:\\Program',
  path: '"C:\\Program',
  spawnargs: [
    'Files\\LibreOffice\\program\\soffice.exe"',
    '-env:UserInstallation=file://C:\\Users\\Roman\\AppData\\Local\\Temp\\soffice-11300-d9d9mKfvSSfo',
    '--headless',
    '--convert-to',
    '.pdf',
    '--outdir',
    'C:\\Users\\Roman\\AppData\\Local\\Temp\\libreofficeConvert_-11300-wBV3EUYjmTul',
    'C:\\Users\\Roman\\AppData\\Local\\Temp\\libreofficeConvert_-11300-wBV3EUYjmTul\\source'
  ],
  cmd: '"C:\\Program Files\\LibreOffice\\program\\soffice.exe" -env:UserInstallation=file://C:\\Users\\Roman\\AppData\\Local\\Temp\\soffice-11300-d9d9mKfvSSfo --headless --convert-to .pdf --outdir C:\\Users\\Roman\\AppData\\Local\\Temp\\libreofficeConvert_-11300-wBV3EUYjmTul C:\\Users\\Roman\\AppData\\Local\\Temp\\libreofficeConvert_-11300-wBV3EUYjmTul\\source'
}
```
