### ISSUE TITLE
Error: Could not find soffice binary

### ISSUE THREAD

**Issue by HadiScript** [elwerene/libreoffice-convert#85]
my app is prefectly running on local machine but on heroku its giving me a error, 
 Error: Could not find soffice binary
2022-06-23T07:45:26.091735+00:00 app[web.1]:     at /app/node_modules/libreoffice-convert/index.js:39:41
2022-06-23T07:45:26.091735+00:00 app[web.1]:     at /app/node_modules/async/dist/async.js:2965:13
2022-06-23T07:45:26.091736+00:00 app[web.1]:     at wrapper (/app/node_modules/async/dist/async.js:271:20)
2022-06-23T07:45:26.091736+00:00 app[web.1]:     at iteratorCallback (/app/node_modules/async/dist/async.js:501:17)
2022-06-23T07:45:26.091736+00:00 app[web.1]:     at /app/node_modules/async/dist/async.js:327:20
2022-06-23T07:45:26.091737+00:00 app[web.1]:     at /app/node_modules/async/dist/async.js:2957:17
2022-06-23T07:45:26.091737+00:00 app[web.1]:     at /app/node_modules/libreoffice-convert/index.js:36:68
2022-06-23T07:45:26.091737+00:00 app[web.1]:     at FSReqCallback.oncomplete (node:fs:188:23)
2022-06-23T07:45:56.072200+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST

**Comment by lincong1498** [comment]
I have the same question and I have already install linuxserver/libreoffice image in my docker

**Comment by kevindesousa** [comment]
I have the same problem, any solutions ?

**Comment by rajeshwarpatlolla** [comment]
It's still an issue. Why is it even closed without solving or answering?
