### ISSUE TITLE
In windows if we are going to delete a folder it won't allow to delete the folder unless it is empty.

### ISSUE THREAD

**Issue by kirithiv2000** [elwerene/libreoffice-convert#87]
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\...\AppData\Local\Temp\libreofficeConvert_-14784-6r6ph8TQRyqc'
    at Object.rmdirSync (fs.js:890:10)
    at rmkidsSync (C:\Users\...\node_modules\rimraf\rimraf.js:349:27)
    at rmdirSync (C:\Users\...\node_modules\rimraf\rimraf.js:329:7)
    at rimrafSync (C:\Users\...\node_modules\rimraf\rimraf.js:301:9)
    at Object._cleanupCallback [as removeCallback] (C:\Users\...\node_modules\tmp\lib\tmp.js:356:16)
    at C:\Users\...\node_modules\libreoffice-convert\index.js:63:17
    at wrapper (C:\Users\...\node_modules\async\dist\async.js:271:20)
    at C:\Users\...\node_modules\async\dist\async.js:1143:21
    at C:\Users\...\node_modules\async\dist\async.js:327:20
    at C:\Users\...\node_modules\libreoffice-convert\index.js:39:32 {
  errno: -4051,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: 'C:\\Users\\...\\AppData\\Local\\Temp\\libreofficeConvert_-14784-6r6ph8TQRyqc'
}

**Comment by WafiqSalie** [comment]
no solution for this yet? been struggling for days :(

**Comment by David-Elkabas** [comment]
I have the same error..

**Comment by David-Elkabas** [comment]
the way I solved it was to download LibreOffice.
you can download it from here:
https://www.libreoffice.org/download/download-libreoffice/

**Comment by elwerene** [comment]
You solved it, good :)
